import type { Metadata } from "next";
import "@peddleon/ped-ux-template-library/dist/styles/base.css";
import "@peddleon/ped-ux-template-library/dist/index.css";
import { FluidRoot } from "@peddleon/ped-ux-react-library";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <FluidRoot>{children}</FluidRoot>
      </body>
    </html>
  );
}
